import styles from './../../styles/components/Tabs/ProductPageTechTabContentMobile.module.sass'

const ProductPageTechTabContentMobile = () => {
    return (
        <div className={styles.product_page_tech_tab_content_mobile}>
            <ul className={styles.product_page_tech_tab_content_mobile__list}>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Производитель:
                    </div>
                    <div
                        style={{ textDecoration: 'underline' }}
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Волхова
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Страна бренда:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Россия
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Страна производитель:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Россия
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Гарантия:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        2 года
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Высота изголовтя, см:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        73
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Форма:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Прямоугольная
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Материал каркаса:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        ЛДСП
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Основание:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Доп.опция
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Возможные опции:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Реечное основание (настил)
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Декор:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Без декора
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Углы каркаса кровати:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Прямые
                    </div>
                </li>
                <li
                    className={
                        styles.product_page_tech_tab_content_mobile__list_item
                    }
                >
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_left
                        }
                    >
                        Матрас:
                    </div>
                    <div
                        className={
                            styles.product_page_tech_tab_content_mobile__list_item_right
                        }
                    >
                        Приобретается отдельно
                    </div>
                </li>
            </ul>
        </div>
    )
}

export default ProductPageTechTabContentMobile
