import { SlideDown } from 'react-slidedown'

// Styles
import citychoise_styles from './../../../styles/components/Header/CityChoiseDesktop/CityChoiseDesktop.module.sass'

const CityChoiseDesktop = ({ closed, setClosed }) => {
    return (
        <SlideDown closed={closed} className={citychoise_styles.city_choise}>
            <div className={citychoise_styles.city_choise__sections}>
                <div className={citychoise_styles.city_choise__moscow}>
                    <div
                        className={citychoise_styles.city_choise__title_section}
                    >
                        Москва и МО
                    </div>
                    <ul className={citychoise_styles.city_choise__list}>
                        <li>Москва</li>
                        <li>Жуковский</li>
                        <li>Балашиха</li>
                        <li>Железнодорожный</li>
                        <li>Клин</li>
                        <li>Коломна</li>
                        <li>Королев</li>
                        <li>Красногорвск</li>
                        <li>Люберцы</li>
                        <li>Мытищи</li>
                        <li>Ногинск</li>
                        <li>Одинцово</li>
                        <li>Орехово-Зуево</li>
                        <li>Подольск</li>
                        <li>Пушкино</li>
                        <li>Раменское</li>
                        <li>Сергиев Посад</li>
                        <li>Серпухов</li>
                        <li>Химки</li>
                        <li>Щёлково</li>
                        <li>Электросталь</li>
                    </ul>
                </div>
                <div className={citychoise_styles.city_choise__regions}>
                    <div
                        className={citychoise_styles.city_choise__title_section}
                    >
                        Регионы
                    </div>
                    <div className={citychoise_styles.city_choise__lists}>
                        <div className={citychoise_styles.city_choise__column}>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    А
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Ангарск</li>
                                    <li>Архангельск</li>
                                    <li>Астрахань</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Б
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Барнаул</li>
                                    <li>Белгород</li>
                                    <li>Брянск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    В
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Владивосток</li>
                                    <li>Владикавказ</li>
                                    <li>Владимир</li>
                                    <li>Волгоград</li>
                                    <li>Вологда</li>
                                    <li>Воронеж</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Е
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Екатеринбург</li>
                                </ul>
                            </div>
                        </div>
                        <div className={citychoise_styles.city_choise__column}>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    И
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Иваново</li>
                                    <li>Ижевск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    К
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Казань</li>
                                    <li>Калининград</li>
                                    <li>Калуга</li>
                                    <li>Кемерово</li>
                                    <li>Киров</li>
                                    <li>Кострома</li>
                                    <li>Краснодар</li>
                                    <li>Красноярск</li>
                                    <li>Курган</li>
                                    <li>Курск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Л
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Липецк</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    М
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Магнитогорвск</li>
                                    <li>Мурманск</li>
                                </ul>
                            </div>
                        </div>
                        <div className={citychoise_styles.city_choise__column}>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Н
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Набережные Челны</li>
                                    <li>Нижний Новгород</li>
                                    <li>Новокузнецк</li>
                                    <li>Новосибирск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    О
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Омск</li>
                                    <li>Оренбург</li>
                                    <li>Орёл</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    П
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Пенза</li>
                                    <li>Пермь</li>
                                    <li>Петрозаводск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Р
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Ростов-на-Дону</li>
                                    <li>Рязань</li>
                                </ul>
                            </div>
                        </div>
                        <div className={citychoise_styles.city_choise__column}>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    С
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Самара</li>
                                    <li>Санкт-Петербург</li>
                                    <li>Саратов</li>
                                    <li>Севастополь</li>
                                    <li>Симферополь</li>
                                    <li>Смоленск</li>
                                    <li>Сочи</li>
                                    <li>Ставрополь</li>
                                    <li>Сургут</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Т
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Тамбов</li>
                                    <li>Тверь</li>
                                    <li>Тольятти</li>
                                    <li>Томск</li>
                                    <li>Тула</li>
                                    <li>Томск</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    У
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Ульяновск</li>
                                    <li>Уфа</li>
                                </ul>
                            </div>
                        </div>
                        <div className={citychoise_styles.city_choise__column}>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Ч
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Чебоксары</li>
                                    <li>Челябинск</li>
                                    <li>Череповец</li>
                                    <li>Чита</li>
                                </ul>
                            </div>
                            <div
                                className={
                                    citychoise_styles.city_choise__wrapper
                                }
                            >
                                <span
                                    className={
                                        citychoise_styles.city_choise__list_title
                                    }
                                >
                                    Я
                                </span>
                                <ul
                                    className={
                                        citychoise_styles.city_choise__list
                                    }
                                >
                                    <li>Якутск</li>
                                    <li>Ярославль</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div
                        onClick={() => {
                            setClosed(true)
                        }}
                        className={citychoise_styles.city_choise__cross}
                    >
                        X
                    </div>
                </div>
            </div>
        </SlideDown>
    )
}

export default CityChoiseDesktop
