import styles from './../../styles/components/Mobile/MobileCityChoise.module.sass'

const MobileBurgerMenuChoiseCity = ({
    onCloseCityList,
    className,
    regions,
}) => {
    const onRegionItemClickHandler = (target) => {
        if (hasWindow) {
            const list = document.querySelectorAll(
                '.' + styles.mobile_burger_menu_city_choise__region_item
            )
            for (let i = 0; i < list.length; i++) {
                if (
                    list[i].querySelector(
                        '.' +
                            styles.mobile_burger_menu_city_choise__grand_letter
                    ).innerHTML === target
                ) {
                    list[i].classList.toggle(styles.region_item_opened)
                }
            }
        }
    }

    const hasWindow = typeof window !== 'undefined'

    return (
        <div
            style={{ display: 'block' }}
            className={`${styles.mobile_burger_menu_city_choise} mobile_burger_menu_city_choise__${className}`}
        >
            <div className={styles.container}>
                <div className={styles.mobile_burger_menu_city_choise__labels}>
                    <i
                        onClick={onCloseCityList}
                        className={styles.arrow_left}
                    ></i>
                    <span>Выбор города</span>
                </div>
                <div className={styles.mobile_burger_menu_city_choise__title}>
                    Москва и МО
                </div>
                <ul
                    className={
                        styles.mobile_burger_menu_city_choise__moscow_list
                    }
                >
                    {regions &&
                        regions.moscow.map((region, id) => {
                            return (
                                <li key={id}>
                                    <label
                                        className={
                                            styles.main_filter__checkbox_container
                                        }
                                    >
                                        <input type="checkbox" />
                                        <span
                                            className={
                                                styles.main_filter__checkmark
                                            }
                                        ></span>
                                        <div
                                            className={
                                                styles.mobile_burger_menu_city_choise__moscow_city_name
                                            }
                                        >
                                            {region.title}
                                        </div>
                                    </label>
                                </li>
                            )
                        })}
                </ul>
                <div className={styles.mobile_burger_menu_city_choise__title}>
                    Регионы
                </div>
                {/* {regions.other.map((region, id) => {
                    return <div className="mobile-burger-menu-city-choise__region-item" onClick={() => region}></div>
                })} */}
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('А')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        А
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ангарск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Архангельск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Астрахань
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Б')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Б
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Барнаул
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Белгород
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Брянск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('В')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        В
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Владивосток
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Владикавказ
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Владимир
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Волгоград
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Вологда
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Воронеж
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Е')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Е
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Екатеринбург
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('И')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        И
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Иваново
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ижевск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('К')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        К
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Казань
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Калининград
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Калуга
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Кемерово
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Киров
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Кострома
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Краснодар
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Красноярск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Курган
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Курск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Л')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Л
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Липецк
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('М')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        М
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Магнитогорск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Мурманск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Н')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Н
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Набережные Челны
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Нижний Новгород
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Новокузнецск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Новосибирск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('О')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        О
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Омск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Орёл
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Оренбург
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('П')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        П
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Пенза
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Пермь
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Петрозаводск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Р')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Р
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ростов-на-Дону
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Рязань
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('С')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        С
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Самара
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Санкт-Петербург
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Саратов
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Севастополь
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Симферополь
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Смоленск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Сочи
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ставрополь
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Сургут
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Т')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Т
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Тамбов
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Тверь
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Тольятти
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Томск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Тула
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Тюмень
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('У')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        У
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ульяновск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Уфа
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Х')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Х
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Хабаровск
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Ч')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Ч
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Чебоксары
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Челябинск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Череповец
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Чита
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div
                    className={
                        styles.mobile_burger_menu_city_choise__region_item
                    }
                    onClick={() => onRegionItemClickHandler('Р')}
                >
                    <div
                        className={
                            styles.mobile_burger_menu_city_choise__grand_letter
                        }
                    >
                        Я
                    </div>
                    <ul
                        className={
                            styles.mobile_burger_menu_city_choise__region_list
                        }
                    >
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Якутск
                                </div>
                            </label>
                        </li>
                        <li
                            className={
                                styles.mobile_burger_menu_city_choise__region_list_item
                            }
                        >
                            <label
                                className={
                                    styles.main_filter__checkbox_container
                                }
                            >
                                <input type="checkbox"></input>
                                <span
                                    className={styles.main_filter__checkmark}
                                ></span>
                                <div
                                    className={
                                        styles.mobile_burger_menu_city_choise__moscow_city_name
                                    }
                                >
                                    Ярославль
                                </div>
                            </label>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default MobileBurgerMenuChoiseCity
